spring.application.name=sales-test-1

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/salesdb
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Session TTL (seconds) — 24 hours
app.session.ttl=86400

# Server port
server.port=8080
